### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by DmonteiroD** [hamidfzm/Flask-HTMLmin#1]
I don't know exactly why, but the example doesn't work in my environment. No minify output.

However your other answer works fine. 

http://stackoverflow.com/a/26139704/564979

ty

**Comment by hamidfzm** [comment]
Can you show me your environment? did you provide `MINIFY_PAGE` option in your flask application config?

**Comment by DmonteiroD** [comment]
https://justpaste.it/sdmt

I tried the example in two different environments (more or less the same pip packages). Just copy paste the example, and no minifty output. 

debian/ubuntu server
