### ISSUE TITLE
OpenTagNotFoundError() redirect code 302

### ISSUE THREAD

**Issue by citijk** [hamidfzm/Flask-HTMLmin#10]
https://github.com/hamidfzm/Flask-HTMLmin/blob/82f828bc6a39d2672bfd152db353e0ee563b48c1/flask_htmlmin.py#L32

if you use flask.redirect, this redirection with code 302 and the response: https://github.com/pallets/werkzeug/blob/4397e61daf66ad43bd5668741c5d876de116a71f/werkzeug/utils.py#L373
```
'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n'
'<title>Redirecting...</title>\n'
'<h1>Redirecting...</h1>\n'
'<p>You should be redirected automatically to target URL: '
'<a href="%s">%s</a>. If not click the link.'
```
for htmlmin.parser is not valid:
https://github.com/mankyd/htmlmin/blob/dff1163a1ec25fe94aeaeefe702377b5a9e912b3/htmlmin/parser.py#L261

that gives an error OpenTagNotFoundError()

**Comment by hamidfzm** [comment]
Any suggestions on how to solve this?
For example checking `response.status_code` and skipping response modification when we encountered `302`?

**Comment by citijk** [comment]
@hamidfzm Most likely the problem appeared after the changes:
https://github.com/hamidfzm/Flask-HTMLmin/commit/7be58047e81f770ad1185282d92884210d7868c9

enough to put
```
        self.html_minify = Minifier(
            **self.default_options)
```
in `def response_minify` and everything works

**Comment by citijk** [comment]
I think the class of `htmlmin.Minifier` is not sufficiently tested. And most likely, the question to him.

**Comment by hamidfzm** [comment]
I will check this class and if i couldn't fix this problem I will `revert` project to use `minify` function .

**Comment by jfunez** [comment]
here they are pointing that the error occurs only with FlaskHTMLmin (with examples using both methods with and without FlaskHTMLmin):
https://github.com/mankyd/htmlmin/issues/46

**Comment by ChristophBerg** [comment]
Fwiw, if it helps anyone, I put this workaround patch into the Debian package of flask-htmlmin to get pgadmin4 working:
```
--- a/flask_htmlmin.py
+++ b/flask_htmlmin.py
@@ -1,4 +1,6 @@
+import logging
 from htmlmin import Minifier
+from htmlmin.parser import OpenTagNotFoundError
 
 __author__ = 'Hamid FzM'
 
@@ -31,9 +33,13 @@ class HTMLMIN(object):
         """
         if response.content_type == u'text/html; charset=utf-8':
             response.direct_passthrough = False
-            response.set_data(
-                self.html_minify.minify(response.get_data(as_text=True))
-            )
+            data = response.get_data(as_text=True)
+            try:
+                minified = self.html_minify.minify(data)
+            except OpenTagNotFoundError:
+                minified = data
+                logging.error('Could not minify data: OpenTagNotFoundError')
+            response.set_data(minified)
 
             return response
         return response
```

**Comment by hamidfzm** [comment]
Please create a pull request @ChristophBerg

**Comment by ChristophBerg** [comment]
Created #11 now - I had not realized this workaround would qualify as a proper patch. Thanks for considering!

**Comment by citijk** [comment]
I found a condition where such an error occurs. 
https://github.com/mankyd/htmlmin/issues/46#issuecomment-349597776

**Comment by sebbekarlsson** [comment]
I'm getting the same error

**Comment by Markus00000** [comment]
mankyd/htmlmin#46 has been fixed.

> Fix bug that can occur when minifying two pages in a row when the first page has a dangling tag.
