### ISSUE TITLE
utf8 crash

### ISSUE THREAD

**Issue by ra-esmith** [hamidfzm/Flask-HTMLmin#16]
Hello

Tried out the module .. ran into an error.
 [2018-08-01 11:14:04 +0000] [2320] [INFO] Starting gunicorn 19.9.0
 [2018-08-01 11:14:04 +0000] [2320] [INFO] Listening at: http://0.0.0.0:5000 (2320)
 [2018-08-01 11:14:04 +0000] [2320] [INFO] Using worker: gevent
 [2018-08-01 11:14:04 +0000] [2324] [INFO] Booting worker with pid: 2324
 [2018-08-01 11:14:04 +0000] [2325] [INFO] Booting worker with pid: 2325
 [2018-08-01 11:14:09 +0000] [2325] [ERROR] Error handling request /
 Traceback (most recent call last):
   File "/home/anon/miniconda2/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
     self.handle_request(listener_name, req, client, addr)
   File "/home/anon/miniconda2/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
     addr)
   File "/home/anon/miniconda2/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
     respiter = self.wsgi(environ, resp.start_response)
   File "/home/anon/miniconda2/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
     return self.wsgi_app(environ, start_response)
   File "/home/anon/miniconda2/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
     response = self.handle_exception(e)
   File "/home/anon/miniconda2/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
     reraise(exc_type, exc_value, tb)
   File "/home/anon/miniconda2/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
     response = self.full_dispatch_request()
   File "/home/anon/miniconda2/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
     return self.finalize_request(rv)
   File "/home/anon/miniconda2/lib/python2.7/site-packages/flask/app.py", line 1833, in finalize_request
     response = self.process_response(response)
   File "/home/anon/miniconda2/lib/python2.7/site-packages/flask/app.py", line 2112, in process_response
     response = handler(response)
   File "/home/anon/miniconda2/lib/python2.7/site-packages/flask_htmlmin/__init__.py", line 35, in response_minify
     self.html_minify.minify(response.get_data(as_text=True))
   File "/home/anon/miniconda2/lib/python2.7/site-packages/werkzeug/wrappers.py", line 989, in get_data
     rv = rv.decode(self.charset)
   File "/home/anon/miniconda2/lib/python2.7/encodings/utf_8.py", line 16, in decode
     return codecs.utf_8_decode(input, errors, True)
 UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by ra-esmith** [comment]
Sorry what sample code?

I just tried it out in my app and got that error.

And then removed it …

Figured you would want to know.

No worries.

Evan

**Comment by VelizarVESSELINOV** [comment]
@mrf345 @hamidfzm  I got the same problem, it is unclear what makes it crash, was working a few days ago, from the many changes in the meantime I don't see a clear root cause of the crash except that started to use dash-plotly, so maybe some flask call conflicts, to solve the issue just disabled the HTMLMIN.

```
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1833, in finalize_request
    response = self.process_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2112, in process_response
    response = handler(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_htmlmin/__init__.py", line 46, in response_minify
    self._html_minify.minify(response.get_data(as_text=True))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/werkzeug/wrappers.py", line 989, in get_data
    rv = rv.decode(self.charset)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
INFO:werkzeug:127.0.0.1 - - [15/Jan/2019 18:21:25] "GET / HTTP/1.1" 500 -
```

**Comment by hamidfzm** [comment]
@VelizarVESSELINOV Can you share sample code to reproduce this issue?

**Comment by ra-esmith** [comment]
Note really … huge application …

**Comment by ra-esmith** [comment]
Hello,

Here are more “logs”.  Does this help at all?  Tryhing to break it down more …


HMS-Surprise:precast-master evan$ startup.sh

Note: Running minify on static precast javascript files

Note:  may wish to use a fresh reset browser to be sure pick up .min.js files!

Running on: "thunder"

[OKAY] Loaded ENV .env File as KEY=VALUE Format

4:42:24 PM web.1 |  [2019-01-18 16:42:24 -0500] [28833] [INFO] Starting gunicorn 19.9.0

4:42:24 PM web.1 |  [2019-01-18 16:42:24 -0500] [28833] [INFO] Listening at: http://0.0.0.0:5000 (28833)

4:42:24 PM web.1 |  [2019-01-18 16:42:24 -0500] [28833] [INFO] Using worker: gevent

4:42:24 PM web.1 |  [2019-01-18 16:42:24 -0500] [28842] [INFO] Booting worker with pid: 28842

4:42:25 PM web.1 |  [2019-01-18 16:42:25 -0500] [28843] [INFO] Booting worker with pid: 28843

4:42:31 PM web.1 |  [2019-01-18 16:42:31 -0500] [28843] [ERROR] Error handling request /

4:42:31 PM web.1 |  Traceback (most recent call last):

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle

4:42:31 PM web.1 |      self.handle_request(listener_name, req, client, addr)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request

4:42:31 PM web.1 |      addr)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request

4:42:31 PM web.1 |      respiter = self.wsgi(environ, resp.start_response)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__

4:42:31 PM web.1 |      return self.wsgi_app(environ, start_response)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app

4:42:31 PM web.1 |      response = self.handle_exception(e)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception

4:42:31 PM web.1 |      reraise(exc_type, exc_value, tb)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app

4:42:31 PM web.1 |      response = self.full_dispatch_request()

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request

4:42:31 PM web.1 |      return self.finalize_request(rv)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1833, in finalize_request

4:42:31 PM web.1 |      response = self.process_response(response)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 2112, in process_response

4:42:31 PM web.1 |      response = handler(response)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_minify/__init__.py", line 68, in toLoopTag

4:42:31 PM web.1 |      text = response.get_data(as_text=True)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/werkzeug/wrappers.py", line 989, in get_data

4:42:31 PM web.1 |      rv = rv.decode(self.charset)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode

4:42:31 PM web.1 |      return codecs.utf_8_decode(input, errors, True)

4:42:31 PM web.1 |  UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte

4:42:31 PM web.1 |  [2019-01-18 16:42:31 -0500] [28843] [ERROR] Error handling request /favicon.ico

4:42:31 PM web.1 |  Traceback (most recent call last):

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle

4:42:31 PM web.1 |      self.handle_request(listener_name, req, client, addr)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request

4:42:31 PM web.1 |      addr)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request

4:42:31 PM web.1 |      respiter = self.wsgi(environ, resp.start_response)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__

4:42:31 PM web.1 |      return self.wsgi_app(environ, start_response)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app

4:42:31 PM web.1 |      response = self.handle_exception(e)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception

4:42:31 PM web.1 |      reraise(exc_type, exc_value, tb)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app

4:42:31 PM web.1 |      response = self.full_dispatch_request()

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request

4:42:31 PM web.1 |      return self.finalize_request(rv)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1833, in finalize_request

4:42:31 PM web.1 |      response = self.process_response(response)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 2112, in process_response

4:42:31 PM web.1 |      response = handler(response)

4:42:31 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask_minify/__init__.py", line 65, in toLoopTag

4:42:31 PM web.1 |      request.url_rule.rule in self.bypass

4:42:31 PM web.1 |  AttributeError: 'NoneType' object has no attribute 'rule'

**Comment by ra-esmith** [comment]
Perhaps it is useful to know this also seems to occur for us in python 3.6 …


[OKAY] Loaded ENV .env File as KEY=VALUE Format

4:49:42 PM web.1 |  /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.

4:49:42 PM web.1 |    """)

4:49:42 PM web.1 |  [2019-01-18 16:49:42 -0500] [29735] [INFO] Starting gunicorn 19.9.0

4:49:42 PM web.1 |  [2019-01-18 16:49:42 -0500] [29735] [INFO] Listening at: http://0.0.0.0:5000 (29735)

4:49:42 PM web.1 |  [2019-01-18 16:49:42 -0500] [29735] [INFO] Using worker: gevent

4:49:42 PM web.1 |  [2019-01-18 16:49:42 -0500] [29739] [INFO] Booting worker with pid: 29739

4:49:42 PM web.1 |  [2019-01-18 16:49:42 -0500] [29741] [INFO] Booting worker with pid: 29741

4:49:50 PM web.1 |  /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gunicorn/workers/ggevent.py:65: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util (/Library/Frameworks/Python.framework/Versions/3.

4:49:50 PM web.1 |  >  6/lib/python3.6/site-packages/urllib3/util/__init__.py)', 'urllib3.util.ssl_ (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/ssl_.py)'].

4:49:50 PM web.1 |    monkey.patch_all(subprocess=True)

4:49:50 PM web.1 |  [2019-01-18 16:49:50 -0500] [29741] [ERROR] Error handling request /

4:49:50 PM web.1 |  Traceback (most recent call last):

4:49:50 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 56, in handle

4:49:50 PM web.1 |      self.handle_request(listener_name, req, client, addr)

4:49:50 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request

4:49:50 PM web.1 |      addr)

4:49:50 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request

4:49:50 PM web.1 |      respiter = self.wsgi(environ, resp.start_response)

4:49:50 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__

4:49:50 PM web.1 |      return self.wsgi_app(environ, start_response)

4:49:50 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app

4:49:50 PM web.1 |      response = self.handle_exception(e)

4:49:50 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception

4:49:50 PM web.1 |      reraise(exc_type, exc_value, tb)

4:49:50 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise

4:49:50 PM web.1 |      raise value

4:49:50 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app

4:49:50 PM web.1 |      response = self.full_dispatch_request()

4:49:50 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request

4:49:50 PM web.1 |      return self.finalize_request(rv)

4:49:50 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1833, in finalize_request

4:49:50 PM web.1 |      response = self.process_response(response)

4:49:50 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2112, in process_response

4:49:50 PM web.1 |      response = handler(response)

4:49:50 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_minify/__init__.py", line 68, in toLoopTag

4:49:50 PM web.1 |      text = response.get_data(as_text=True)

4:49:50 PM web.1 |    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/werkzeug/wrappers.py", line 989, in get_data

4:49:50 PM web.1 |      rv = rv.decode(self.charset)

4:49:50 PM web.1 |  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by ra-esmith** [comment]
It may be that Flask_Compress does not play well with flask_minify.

I am finding I get “new errors” with minifiy when I comment out our flask_compress

After turning off compress, I get the error
SyntaxError: missing catch or finally after try

In firefox console (debugger).

And it looks like minifiy did do something!  But I had to turn off compress … and I have this error which is making stuff not work…

**Comment by hamidfzm** [comment]
This is so messed up. But I think you are using flask minify.

**Comment by ra-esmith** [comment]
Ah, yes I tried flask-minify after I could not get flask-htmlmin to work 😊

Righ sorry, will go back to flask-htmlmin

**Comment by hamidfzm** [comment]
Can you share code snippet for the route causing this issue?

**Comment by ra-esmith** [comment]
Ok, I put in your stuff (flask-htmlmin) and removed flask-minify, sorry.

And it worked!  But then I put back flask compress, to see what that would do … and yep got back the error!
So it is compress and flkas html min that is the issue.

So the following, starts up fine … but is returning a bad page!

5:00:22 PM web.1 |  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

But it is the “compress” with htmlmin that is the issue …  no idea why


from __future__ import print_function

import json
import logging
import os

from flask import Flask
from flask_caching import Cache
from flask_compress import Compress
from flask_peewee.db import Database
from flask_sslify import SSLify
from flask_htmlmin import HTMLMIN

cache = None
try:
    oak_app = Flask(__name__)
    oak_app.config['MINIFY_PAGE'] = True
    htmlmin = HTMLMIN(oak_app)

    oak_app.logger.setLevel(logging.ERROR)
    Compress(oak_app)
    oak_app.debug = False
    sslify = SSLify(oak_app)
    oak_app.jinja_env.globals.update(len=len, dumps=json.dumps)
    if 'ON_HEROKU' in os.environ:
        oak_app.config.from_object('oak_config.ProductionConfig')
        cache = Cache(oak_app, config={'CACHE_TYPE': 'filesystem', 'CACHE_DIR': 'cache'})
    else:
        oak_app.config.from_object('oak_config.DevelopmentConfig')
        cache = Cache(oak_app, config={'CACHE_TYPE': 'simple'})
        # cache = Cache(app, config={'CACHE_TYPE': 'filesystem', 'CACHE_DIR': 'cache'})
    db = Database(oak_app)

except Exception as e:
    print("Exception: " + str(e))

**Comment by ra-esmith** [comment]
And it appears to by any route … meaning all one needs to do is use flask compress to and htmlmin to see this error.

Now does one need both?  Perhaps that is not needed?

Also when I am in the “firefox debugger” the htmlmin “unwraps” stuff so I can see the original html … is that normal?  Can I mangle the internal javascript much like I do with uglify on raw javascript?

Evan

**Comment by mrf345** [comment]
@ra-esmith I don't really know what sort of result do expect by running a deprecated package that attempts to compress the response with gzip! while the minifiers are trying to read the response as a UTF-8 text.

https://webcache.googleusercontent.com/search?q=cache:qf5Pzw4phuYJ:https://github.com/jmcarp/flask-compress+&cd=3&hl=en&ct=clnk&gl=my

**Comment by akcode47** [comment]
I am seeing UnicodeDecodeError errors as well when I have app.config['MINIFY_HTML'] = True.

I am using Flask-Compress along with Flask-HTMLmin. 

The error goes away if I set MINIFY_HTML to False, but that defeats the point of using the library. 

The API route I have is just a render_template call to a bootstrap HTML page.

Error: 

htmlmin UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 7: invalid start byte

**Comment by akcode47** [comment]
For anyone who is running into a UnicodeDecodeError issue and is using other flask extensions like Flask-CORs and Flask-Compress the order in which you initialize matters. 

Moving the HTMLmin initialization after the other libraries allowed it to work as expected for me. This applies to the non-related Flask-Minify library as well.

Initialize the minifier after other extensions.
