### ISSUE TITLE
Can we read htmlmin options from the flask config file?

### ISSUE THREAD

**Issue by christopherpickering** [hamidfzm/Flask-HTMLmin#21]
Hi, thanks for the tool!

What do you think about allowing these settings to be set in the app.config?
```python
default_options = {
            'remove_comments': True,
            'reduce_empty_attributes': True,
            'remove_optional_attribute_quotes': False
        }
default_options.update(kwargs)
```

As well as the other options for htmlmin from https://htmlmin.readthedocs.io/en/latest/reference.html?

Personally, I'd really like to add the "remove_empty_space". Somehow my output has whitespace between all tags, for example the closing tags on my homepage look like this -
```html
</div> </div> </div> </body> </html>
```

**Comment by hamidfzm** [comment]
You can override the default options or pass extra ones on extension initialization:

```python
from flask import Flask, render_template
from flask_htmlmin import HTMLMIN
    
app = Flask(__name__)
app.config['MINIFY_HTML'] = True

htmlmin = HTMLMIN(app, remove_comments=False, remove_empty_space=True)

@app.route('/')
def main():
    # index.html will be minimized !!!
    return render_template('index.html')

if __name__ == '__main__':
    app.run()
```

**Comment by christopherpickering** [comment]
awesome, thanks!
